# Example documentation with all widgets, parameters, values and defaults

Screen:
  # [default values when not declared, see below]
  # screenName:                               ScreenID   [required] (main: first displayed screen)
  #     display:                              display    [required] contains graphical elements
  #
  #         # COMMON properties
  #         - Type:                           widgetType [required] Your favorite widget
  #                 box                                   - Draw a box
  #                 button                                - Draw a button (just like a box but pretty with a text caption)
  #                 text                                  - Print some text on the screen (centered on X,Y)
  #                 windowdialog                          - Draw a modal window like box (confirm, info, errors, ...)
  #                 dot                                   - Draw a single dot on the screen
  #                 circle                                - Draw a circle
  #                 crosshair                             - Draw a crosshair (useful for calibration stuff)
  #           id: widgetID                    widgetID   [optional] Widget ID
  #           x: 10                           Integer    [optional] X Position for the widget
  #           y: 10                           Integer    [optional] Y Position for the widget
  #           color: 255,255,255              Tuple      [optional] Widget color
  #           action: None                    String     [optional] Action associated to this widget
  #           t_x1: <calc>                    Touch Xmin [optional] Touchscreen interface X min (calculated or manually set)
  #           t_y1: <calc>                    Touch Ymin [optional] Touchscreen interface Y min (calculated or manually set)
  #           t_x2: <calc>                    Touch Xmax [optional] Touchscreen interface X max (calculated or manually set)
  #           t_y2: <calc>                    Touch Ymax [optional] Touchscreen interface Y max (calculated or manually set)
  #                                           t_x1 < t_x2,   t_y1 < t_y2     [[ !ALWAYS! ]]
  #
  #         # [BOX] extra properties
  #           width: 100                      Integer    [optional] Widget width
  #           height: 50                      Integer    [optional] Widget height
  #           border: 0                       Integer    [optional] Widget border
  #           bordercolor: 255,255,255        Tuple      [optional] Widget default color (RGB)
  #
  #         # [BUTTON] extra properties       Inherits properties from [BOX]
  #           border: 2                       Integer    [optional] Button border
  #           text: 'button'                  Text       [optional] Button caption
  #           textsize: 24                    Integer    [optional] Button caption font size
  #           textcolor: 255,255,255          Tuple      [optional] Button caption color (and top left border button color)
  #           bordercolor: 255,255,255        Tuple      [optional] Color of the bottom right part of the button
  #
  #         # [TEXT] extra properties
  #           text: 'button'                  Text       [optional] Text label
  #           textalign: (left|center|right)  Enum       [optional] Text alignment (default: center)
  #           textsize: 24                    Integer    [optional] Text font size
  #           textcolor: 255,255,255          Tuple      [optional] Text color. [color] AND [textcolor] are the same property
  #
  #         # [WINDOWDIALOG] extra properties
  #           width:  250                     Integer    [optional] Widget width
  #           height: 100                     Integer    [optional] Widget height
  #           title: 'window title'           Text       [optional] Window title
  #           titlebackground: 20,50,70       Tuple      [optional] Window title background color
  #           color: 50,188,228               Tuple      [optional] Widget color (window color)
  #           bordercolor, 120,120,120        Tuple      [optional] Widget border color (buttons and window)
  #           text: 'info message'            Text       [optional] Text message
  #           textsize: 18                    Integer    [optional] Window message text size
  #           textcolor: 255,255,255          Tuple      [optional] Text color
  #           textalign: (left|center|right)  Enum       [optional] Window message alignment, default: left
  #           button1: '  OK  '               Text       [optional] Button 1 text, if [None] button won't be displayed
  #           button2:  CANCEL                Text       [optional] Button 2 text, if [None] button won't be displayed
  #           buttoncolor: 50,188,228         Tuple      [optional] Buttons background color
  #           buttontextcolor: 0,0,0          Tuple      [optional] Buttons text color
  #           action:  None                   String     [optional] Action associated to button1
  #           action2: None                   String     [optional] Action associated to button2
  #
  #         # [DOT] extra properties (none)
  #
  #         # [CIRCLE]    properties ..and..
  #         # [CROSSHAIR] properties
  #           fill: true|false                Boolean    [optional] Fill the crosshair (with [color])
  #           radius: 10                      Integer    [optional] Crosshair radius
  main:
    Display:
      - Type: box
        id: box1
        x: 5
        y: 10
        width: 20
        height: 30
        color: 100,50,191
        action: exit
      - type: box
        id: box2
        x: 50
        y: 100
        width: 70
        height: 30
        border: 1
      - type: dot
        x: 160
        y: 120
        color: 255,255,255
      - type: dot
        x: 00
        y: 120
        color: 255,255,255
      - type: dot
        x: 319
        y: 120
        color: 255,255,255
      - type: button
        id: button1
        x: 100
        y: 30
        width: 100
        height: 30
        text: Hello World
        action: exit
    # events:
